version: '3.3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.5
    hostname: zookeeper
    networks:
      - kafka_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.0.5
    depends_on:
      - zookeeper
    hostname: kafka
    networks:
      - kafka_network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  logger-connector:
    build: ./logger-connector/
    container_name: logger-connector
    networks:
      - kafka_network
    depends_on:
      - kafka
    ports:
      - 8083:8083
    volumes:
      - ./tmp:/tmp
    links:
      - kafka

  http-receiver:
    build: ./http-receiver/
    image: http-receiver
    container_name: http-receiver
    networks:
      - kafka_network
    ports:
      - 8080:8080
    depends_on:
      - kafka
    links:
      - kafka

  processor:
    build: ./processor/
    image: processor
    container_name: processor
    networks:
      - kafka_network
    depends_on:
      - kafka
    links:
      - kafka

networks:
  kafka_network: