version: '3.3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.5
    hostname: zookeeper
    networks:
      - kafka_network
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
      #    environment:
  #      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.0.5
    depends_on:
      - zookeeper
    hostname: kafka
    networks:
      - kafka_network
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#    ports:
#      #      - '9092:9092'
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#  #      KAFKA_MIN_INSYNC_REPLICAS: 1

  init-kafka:
    image: confluentinc/cp-kafka:7.0.5
    depends_on:
      - kafka
    networks:
      - kafka_network
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists \
          --topic consumer-topic \
          --partitions 6 \
          --replication-factor 1

      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists \
          --topic upper-case-text \
          --partitions 6 \
          --replication-factor 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "

  http-receiver:
    build: ./http-receiver/
    image: http-receiver
    container_name: http-receiver
    networks:
      - kafka_network
#    network_mode: host
    ports:
      - 8080:8080
#      - 9092:9092
    depends_on:
      - kafka
    links:
      - kafka
    environment:
      KAFKA_ADDRESS: kafka
      #      - kafka=kafka
      #      - KAFKA_ADDRESS=9092
    command:
      - KAFKA_ADDRESS=kafka

  processor:
    build: ./processor/
    image: processor
    container_name: processor
    networks:
      - kafka_network
    links:
      - kafka
#    ports:
#      - 9092:9092
    depends_on:
      - kafka

networks:
  kafka_network: